load("//build/bazel/rules:blue_cc_module.bzl", "blue_cc_module")

package(default_visibility = ["//visibility:private"])

blue_cc_module(
    name = "BlueContainer",
    srcs = [
        "src/Pch.cpp",
        "src/SmidString.cpp",
        "src/BlueContainerPrivate.h",
        "src/Pch.h",
    ],
    hdrs = [
        "include/Blue/Container.h",
        "include/Blue/Container/Api.h",
        "include/Blue/Container/DynamicArray.h",
        "include/Blue/Container/RingBuffer.h",
        "include/Blue/Container/SmidString.h",
        "include/Blue/Container/Span.h",
        "include/Blue/Container/StringView.h",
        "include/BlueContainer/BlueContainer.h",
        "include/BlueContainer/BlueContainerApi.h",
    ],
    defines = [
        "BLUE_CONTAINER=1",
    ],
    deps = [
        "//modules/BlueMemory:BlueMemory",
        "//modules/BlueSystem:BlueSystem",
    ],
    link_requirement_deps = [
        "//modules/BlueMemory:BlueMemory_link_requirements",
    ],
    local_includes = ["src"],
    shared_dynamic_deps = [
        "//modules/BlueMemory:BlueMemory_shared",
    ],
    shared_local_defines = [
        "BLUE_BUILD_BLUE_CONTAINER=1",
        "BLUE_EXPORT_BlueContainer=1",
    ],
    visibility = ["//visibility:public"],
)
