// Copyright (c) Khaled Shawki. All rights reserved.

#pragma once

#ifndef BLUE_MEMORY_SHIPPING_WITH_STATS
#  define BLUE_MEMORY_SHIPPING_WITH_STATS 0
#endif

#ifndef BLUE_MEMORY_IS_OPTIMIZED_BUILD
#  if ( defined( BLUE_RELEASE ) && BLUE_RELEASE ) || ( defined( BLUE_SHIPPING ) && BLUE_SHIPPING )
#    define BLUE_MEMORY_IS_OPTIMIZED_BUILD 1
#  else
#    define BLUE_MEMORY_IS_OPTIMIZED_BUILD 0
#  endif
#endif

#ifndef BLUE_MEMORY_ENABLE_VALIDATION
#  if BLUE_MEMORY_IS_OPTIMIZED_BUILD
#    define BLUE_MEMORY_ENABLE_VALIDATION 0
#  else
#    define BLUE_MEMORY_ENABLE_VALIDATION 1
#  endif
#endif

#ifndef BLUE_MEMORY_ENABLE_REALLOCATION_VALIDATION
#  if BLUE_MEMORY_IS_OPTIMIZED_BUILD
#    define BLUE_MEMORY_ENABLE_REALLOCATION_VALIDATION 0
#  else
#    define BLUE_MEMORY_ENABLE_REALLOCATION_VALIDATION 1
#  endif
#endif

#ifndef BLUE_MEMORY_ENABLE_TRACKING
#  if ( defined( BLUE_DEBUG ) && BLUE_DEBUG ) || ( defined( BLUE_PROFILE ) && BLUE_PROFILE )
#    define BLUE_MEMORY_ENABLE_TRACKING 1
#  else
#    define BLUE_MEMORY_ENABLE_TRACKING 0
#  endif
#endif

#ifndef BLUE_MEMORY_ENABLE_METRICS
#  if BLUE_MEMORY_IS_OPTIMIZED_BUILD && !BLUE_MEMORY_SHIPPING_WITH_STATS
#    define BLUE_MEMORY_ENABLE_METRICS 0
#  else
#    define BLUE_MEMORY_ENABLE_METRICS 1
#  endif
#endif

#ifndef BLUE_MEMORY_ENABLE_SMALL_BLOCK_STATS
#  if BLUE_MEMORY_ENABLE_METRICS || BLUE_MEMORY_SHIPPING_WITH_STATS
#    define BLUE_MEMORY_ENABLE_SMALL_BLOCK_STATS 1
#  else
#    define BLUE_MEMORY_ENABLE_SMALL_BLOCK_STATS 0
#  endif
#endif

#ifndef BLUE_MEMORY_ENABLE_THREAD_LOCAL_METRICS
#  define BLUE_MEMORY_ENABLE_THREAD_LOCAL_METRICS BLUE_MEMORY_ENABLE_METRICS
#endif

#ifndef BLUE_MEMORY_ENABLE_POOL_ACCOUNTING
#  if BLUE_MEMORY_IS_OPTIMIZED_BUILD && !BLUE_MEMORY_SHIPPING_WITH_STATS
#    define BLUE_MEMORY_ENABLE_POOL_ACCOUNTING 0
#  else
#    define BLUE_MEMORY_ENABLE_POOL_ACCOUNTING 1
#  endif
#endif

#ifndef BLUE_MEMORY_ENABLE_POOL_VALIDATION
#  if BLUE_MEMORY_IS_OPTIMIZED_BUILD
#    define BLUE_MEMORY_ENABLE_POOL_VALIDATION 0
#  else
#    define BLUE_MEMORY_ENABLE_POOL_VALIDATION 1
#  endif
#endif

#ifndef BLUE_MEMORY_ENABLE_OOM_REPORTS
#  if BLUE_MEMORY_IS_OPTIMIZED_BUILD
#    define BLUE_MEMORY_ENABLE_OOM_REPORTS 0
#  else
#    define BLUE_MEMORY_ENABLE_OOM_REPORTS 1
#  endif
#endif

#ifndef BLUE_MEMORY_ENABLE_LIGHTWEIGHT_OOM_CALLBACK
#  define BLUE_MEMORY_ENABLE_LIGHTWEIGHT_OOM_CALLBACK 0
#endif

#ifndef BLUE_MEMORY_ENABLE_LEAK_REPORTS
#  if defined( BLUE_DEBUG ) && BLUE_DEBUG
#    define BLUE_MEMORY_ENABLE_LEAK_REPORTS 1
#  else
#    define BLUE_MEMORY_ENABLE_LEAK_REPORTS 0
#  endif
#endif

#ifndef BLUE_MEMORY_ENABLE_SOURCE_LOCATION
#  if BLUE_MEMORY_IS_OPTIMIZED_BUILD
#    define BLUE_MEMORY_ENABLE_SOURCE_LOCATION 0
#  else
#    define BLUE_MEMORY_ENABLE_SOURCE_LOCATION 1
#  endif
#endif

#ifndef BLUE_MEMORY_ENABLE_ALLOCATION_POISONING
#  define BLUE_MEMORY_ENABLE_ALLOCATION_POISONING 0
#endif

#ifndef BLUE_MEMORY_ENABLE_FREE_POISONING
#  define BLUE_MEMORY_ENABLE_FREE_POISONING 0
#endif

#ifndef BLUE_MEMORY_ENABLE_DOUBLE_FREE_DETECTION
#  define BLUE_MEMORY_ENABLE_DOUBLE_FREE_DETECTION 0
#endif

#ifndef BLUE_MEMORY_ENABLE_STACK_TRACES
#  define BLUE_MEMORY_ENABLE_STACK_TRACES 0
#endif
