load("//build/bazel/rules:blue_cc_module.bzl", "blue_cc_module")

package(default_visibility = ["//visibility:private"])

blue_cc_module(
    name = "BlueJobSystem",
    srcs = [
        "src/JobSystem.cpp",
        "src/Pch.cpp",
        "src/BlueJobSystemPrivate.h",
        "src/Pch.h",
    ],
    hdrs = [
        "include/Blue/JobSystem.h",
        "include/Blue/JobSystem/Api.h",
        "include/Blue/JobSystem/JobSystem.h",
        "include/BlueJobSystem/BlueJobSystem.h",
        "include/BlueJobSystem/BlueJobSystemApi.h",
    ],
    defines = [
        "BLUE_JOB_SYSTEM=1",
    ],
    deps = [
        "//modules/BlueContainer:BlueContainer",
        "//modules/BlueMemory:BlueMemory",
        "//modules/BlueSystem:BlueSystem",
    ],
    link_requirement_deps = [
        "//modules/BlueContainer:BlueContainer_link_requirements",
    ],
    local_includes = ["src"],
    shared_dynamic_deps = [
        "//modules/BlueContainer:BlueContainer_shared",
    ],
    shared_local_defines = [
        "BLUE_BUILD_BLUE_JOB_SYSTEM=1",
        "BLUE_EXPORT_BlueJobSystem=1",
    ],
    visibility = ["//visibility:public"],
)
