// Copyright (c) Khaled Shawki. All rights reserved.

#include <Blue/Memory/Config/BlueMemoryConfig.h>

#include <gtest/gtest.h>

TEST( BlueMemoryConfigTests, BuildProfileFeatureGatesAreStable )
{
#if defined( BLUE_DEBUG ) && BLUE_DEBUG
  EXPECT_EQ( BLUE_MEMORY_ENABLE_VALIDATION, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_REALLOCATION_VALIDATION, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_TRACKING, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_METRICS, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_POOL_ACCOUNTING, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_POOL_VALIDATION, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_OOM_REPORTS, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_LEAK_REPORTS, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_SOURCE_LOCATION, 1 );
#endif

#if defined( BLUE_PROFILE ) && BLUE_PROFILE
  EXPECT_EQ( BLUE_MEMORY_ENABLE_VALIDATION, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_REALLOCATION_VALIDATION, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_TRACKING, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_METRICS, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_POOL_ACCOUNTING, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_POOL_VALIDATION, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_OOM_REPORTS, 1 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_LEAK_REPORTS, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_SOURCE_LOCATION, 1 );
#endif

#if defined( BLUE_RELEASE ) && BLUE_RELEASE
  EXPECT_EQ( BLUE_MEMORY_ENABLE_VALIDATION, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_REALLOCATION_VALIDATION, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_TRACKING, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_METRICS, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_POOL_ACCOUNTING, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_POOL_VALIDATION, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_OOM_REPORTS, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_LEAK_REPORTS, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_SOURCE_LOCATION, 0 );
#endif

#if defined( BLUE_SHIPPING ) && BLUE_SHIPPING
  EXPECT_EQ( BLUE_MEMORY_ENABLE_VALIDATION, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_REALLOCATION_VALIDATION, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_TRACKING, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_METRICS, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_POOL_ACCOUNTING, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_POOL_VALIDATION, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_OOM_REPORTS, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_LEAK_REPORTS, 0 );
  EXPECT_EQ( BLUE_MEMORY_ENABLE_SOURCE_LOCATION, 0 );
#endif
}
